"""Add max_quota_bytes to overleaf_users

Revision ID: 995593f824d9
Revises: f47edfb61396
Create Date: 2026-03-27 02:52:09.352164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '995593f824d9'
down_revision = 'f47edfb61396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overleaf_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_quota_bytes', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overleaf_users', schema=None) as batch_op:
        batch_op.drop_column('max_quota_bytes')

    # ### end Alembic commands ###
