"""add project_sync_logs

Revision ID: eb22496b9099
Revises: a1b2c3d4e5f6
Create Date: 2026-04-27 09:45:59.895967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb22496b9099'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('sync_run_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['overleaf_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_run_id'], ['sync_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_sync_logs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_sync_logs_sync_run_id'), ['sync_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_sync_logs_sync_run_id'))
        batch_op.drop_index(batch_op.f('ix_project_sync_logs_project_id'))

    op.drop_table('project_sync_logs')
    # ### end Alembic commands ###
