"""Add file_count and size_bytes to overleaf_projects

Revision ID: f47edfb61396
Revises: f002dca0dfd2
Create Date: 2026-03-27 02:18:48.625096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47edfb61396'
down_revision = 'f002dca0dfd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overleaf_projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('size_bytes', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('overleaf_projects', schema=None) as batch_op:
        batch_op.drop_column('size_bytes')
        batch_op.drop_column('file_count')

    # ### end Alembic commands ###
